name: Deploy to Local Server dev env

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 72.255.38.176
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: "cd /opt/PythonProjects/Make_tickets/prod/CI-CD && git checkout dev && git branch --set-upstream-to=origin/dev dev && git pull"

      
      # with:
      #   host: ${{ secrets.SSH_HOST }}
      #   username: ${{ secrets.SSH_USERNAME }}
      #   password: ${{ secrets.SSH_PASSWORD }}
      #   port: ${{ secrets.SSH_PORT }}
      #   script: "cd /opt/PythonProjects/Make_tickets/prod/CI-CD && git checkout dev && git branch --set-upstream-to=origin/dev dev && git pull"
