name: remote ssh command

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 192.168.1.100  # Replace with your server's IP address or hostname
        username: muneeb  # Replace with your SSH username
        password: muneeb1234  # Replace with your SSH password
        port: 22  # Replace with your SSH port if different
        script: whoami
